### ISSUE TITLE
Omni set to Google search does use trk-XXX URL

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#1]
From the Ubuntu tracker (https://github.com/iridium-browser/iridium-browser-windows/issues/3), but it is probably an issue for all platforms.

https://trk-192.iridiumbrowser.de/www.google.com/search?q=test&oq=test&sourceid=chrome&es_sm=93&ie=UTF-8

trk-192 seems to be used when searching with Google. We need to check what 192 is used for and let this through to Google directly if only used for searching in the omnibox with Google provider.

**Comment by fancycode** [comment]
This is also called from here:
```
Attempt at loading traced URL: trk:193:https://www.google.com/searchdomaincheck?format=domain&type=chrome
```

**Comment by jengelh** [comment]
Fixed. Whitelisted trk-193 now (post-43.1) on the grounds that it only appears not trigger when not using Google for Omnibox Search.

**Comment by fancycode** [comment]
Why not disable the request completely and always use `google.com` if somebody wants to search using Google?

**Comment by jengelh** [comment]
Dunno, maybe it has to do with language selection (probably not, for that, there would be the Accept-Language: HTTP header), or perhaps locality relevance (i.e. return the German Burger King as 1st result if your geolookup yielded DE despite Accept-Language==en).

I don't particularly care, because Google is not the default in IR anyway.

**Comment by longsleep** [comment]
This should either use google directly (if anyone wants that) or be removed. What does actually happen with the trk-193 white list change?

**Comment by fancycode** [comment]
You will no longer get the JS popup notification about the trk request and the underlying Google request will be executed.

**Comment by longsleep** [comment]
Ok i see. That is fine as long as trk-193 is only used for the omi box if the user manually switched it to search with Google.
