### ISSUE TITLE
Safebrowsing downloads from Google

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser#10]
Safebrowsing data is still downloaded from Google:
```
Attempt at loading traced URL: trk:165:https://safebrowsing.google.com/safebrowsing/downloads?client=chromium&appver=43.1&pver=3.0&key=dummytoken
```

Didn't we already decide to point this to our own server?

**Comment by jengelh** [comment]
Could be some new annoyances introduced by Google recently.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-May/000341.html

**Comment by jengelh** [comment]
The patch does not help if the data is not actually present on cache.iridiumbrowser.de - and since it is not downloadable directly with curl (yields HTTP 400), the patch alone is not enough.

**Comment by fancycode** [comment]
Wasn't the original plan to return a `307` for that URL so the actual data is still fetched from Google?

**Comment by theurere** [comment]
When enabling the Privacy preference "Enable phishing and malware protection" there are now requests for `safebrowsing-cache.google.com` and `safebrowsing.google.com` at tests `4` and `6`

**Comment by fancycode** [comment]
Updated patch: http://lists.inai.de/pipermail/iridium/2015-July/000443.html

**Comment by longsleep** [comment]
307 approach does not work, closing for now as we decided to load from Google and let the user opt out.

**Comment by longsleep** [comment]
See https://github.com/iridium-browser/iridium-browser/wiki/Differences-between-Iridium-and-Chromium#google-safe-browsing for details
