### ISSUE TITLE
Unable to play videos on specific website

### ISSUE THREAD

**Issue by tonialb** [iridium-browser/iridium-browser#101]
![Uploading issue.png…]()
Hello,

What I want from a browser are security, privacy, speed. So after searching on web, I found Iridium. I just installed the latest version on my Win7-64bit-Ultimate computer and seems to work good. 

But doing some tests with my favorite sites, I faced with a problem. On Euronews website, I'm unable to play videos, I mean all of them! This issue appears with both versions 32/64bit. Also I disabled all extensions which I usual use (ublockOtigin, umatrix, flashcontrol, referer control) but seems it doesn't fix the problem. In order to be sure, I installed another Iridium, older version 48.2, but still the same issue "**Error loading media: File could not be played**"! 
Unlike Google Chrome, Cyberfox, Vivaldi, IE11 which I tested. With them I don't have this weird problem.

Is there anything I can do to fix this problem? I like to keep this browser as my default one.

Thank you for your time

**Comment by souldanger** [comment]
Hi Toni,
the problems you are having are down to audio/video codecs, that are not included by default in Iridium for various reasons. However, this will be way better in version 54 that is currently being tested and rolled out hopefully later this month. I can confirm that Euronews audio/video will be fully working in v54.
Please stand by.
Thanks!

**Comment by tonialb** [comment]
Hi souldanger,

Thank you for your information. Keep up the good work. ;-)

thnx

**Comment by souldanger** [comment]
Hi Toni,
version 54.0 for Windows is now available for download @ https://iridiumbrowser.de/download.html
The audio/video extension/codecs that we use now, work way better.
However DRM (i.e. for amazon video or netflix) is still not supported.
Enjoy!
