### ISSUE TITLE
Iridium icon in tasks bar is not the same as the icon in menubar

### ISSUE THREAD

**Issue by nghinv** [iridium-browser/iridium-browser#103]
Hello,

Running iridium in ubuntu 14.04, I see that the icon in tasks bar is the same as chromium-browser. It is not the same as Iridium icon in menubar.

Could you please tell me how to change (workaround) or fix it it?

thanks,

**Comment by souldanger** [comment]
Hi nghinv
we will have a new build for Unbuntu shortly which will fix the issue.
thank you for your patience!

**Comment by souldanger** [comment]
Hello
new Ubuntu / Debian packages are now online [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)
The issue shoiuld be fixed now.
