### ISSUE TITLE
Another Error. this time on Debian.

### ISSUE THREAD

**Issue by 314parley** [iridium-browser/iridium-browser#107]
Hello All! I found an error that only appears to not work on Debian(/Ubuntu?) whenever Iridium is launched, it gives me a fatal error ("Aw Snap" on anything I open on Iridium) . might it be due to the packages not being updated to the latest build? I've attached an image of the error.
![iridium-debian-error](https://cloud.githubusercontent.com/assets/1246441/20326965/ff0c56de-ab3f-11e6-987d-c7159a135896.png)

**Comment by souldanger** [comment]
please install latest version
wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/iridium-browser.list
deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
#deb-src https://downloads.iridiumbrowser.de/deb/ stable main
EOF
sudo apt-get update
sudo apt-get install iridium-browser
