### ISSUE TITLE
Don't use JavaScript alert by default to alert about trk requests

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser#11]
We shouldn't show the JavaScript alert by default when a trk request is performed, but only enable it through a commandline option. At least until we got rid of enough trk requests that the browsing experience is not interrupted constantly.

**Comment by longsleep** [comment]
May be a less intrusive way can be found (e.g. notification). I would like it that we try hard not to make browsing with Iridium a pain, even when we did not eliminate all the hidden requests yet.

**Comment by mikegioia** [comment]
I commented in #9, but I think it's related to this issue. I don't care if these messages log to the terminal or the JS console, or whatever but an alert is just too obtrusive. I can't use the browser currently until the alerts are removed :(

**Comment by longsleep** [comment]
We are aware that the pop ups are too invasive to the work flow. Iridium 43.2 will be released soon and should no longer show pop ups during normal operations. See https://github.com/iridium-browser/iridium-browser/wiki/Releases for the progress.

**Comment by longsleep** [comment]
When such alert is open, the browser is essentially non responsive and kind of "hangs" until it is confirmed. This needs to change asap.

**Comment by mikegioia** [comment]
Thanks, @longsleep

**Comment by fancycode** [comment]
Tentative patch: http://lists.inai.de/pipermail/iridium/2015-June/000371.html

**Comment by fancycode** [comment]
Final patch: http://lists.inai.de/pipermail/iridium/2015-June/000378.html

**Comment by jengelh** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/diff/net-help-identify-URLs-being-retrieved.patch?h=patchview&id=6d41f5b4664ab06f0809fb875a964f1b566e65e9
