### ISSUE TITLE
chrome://newtab background not changed with theme

### ISSUE THREAD

**Issue by packtsardine** [iridium-browser/iridium-browser#110]
The white background of chrome://newtab is blinding, and there doesn't seem to be a way for users to change it. In searching for a solution, I found many people have had this issue with Chrome and/or Chromium in the past and they suggested adding a theme with a dark background to fix the issue.  

The background changes are not applied in Iridium, from what I can tell. The white background remains after applying new themes.

**Comment by souldanger** [comment]
Hello
this is something we won't be able to fix as we're just a small team of developers focusing on privacy and security...
Thank you for your understanding!
