### ISSUE TITLE
Missing portable install from 54.0.0

### ISSUE THREAD

**Issue by szepeviktor** [iridium-browser/iridium-browser#113]
https://downloads.iridiumbrowser.de/windows/54.0.0/
Please consider using a release checklist. It could be in the Wiki.

Danke schön!

**Comment by souldanger** [comment]
Next version, probably v56.x will also have a portable install again.
Apologies for not having one for v 54.

**Comment by szepeviktor** [comment]
Thank you for your response.

Have you seen this project?
https://github.com/Eloston/ungoogled-chromium
It is a more cut-down version of Chromium.

**Comment by kalvinator** [comment]
Hi,

When do you release the next version? Any foreseeable schedule?

Thx...

**Comment by souldanger** [comment]
Hi kalvinator
we are aiming to release v56 approx 2-4weeks after a stable chromium has been released.
However, as Iridium only is a handful of developers all of which also have a job, it might take a longer for the one or other platform.
Thanks
