### ISSUE TITLE
Chrome version in user-agent doesn't match what is actually used

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser#12]
With 43.1, the user-agent contains `Chrome/43.0.2357.84` even though it is based on `.85`. We should find a way to automatically include the correct version instead of having to manually edit this.

**Comment by jengelh** [comment]
The only reason we provide the Chrome/ substring is to please browser detection, and for that, the first part of the version number would even be enough I guess.

**Comment by longsleep** [comment]
Considering how shitty user agent parsers in the wild are, we should keep full Chrome version in UA to avoid issues.

**Comment by jengelh** [comment]
Resolved in 43.5.

**Comment by jengelh** [comment]
WONTFIX. There is no other place where the number appears.
