### ISSUE TITLE
Wrong "cookies" message in omnibox

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser#13]
The omnibox shows the crossed cookie icon even for webpages that have cookies allowed.

![image](https://cloud.githubusercontent.com/assets/247730/7879544/80e2e632-05f1-11e5-8595-5d45fecae93c.png)

**Comment by fancycode** [comment]
This seems to be triggered by the "Block third-party and website data" setting.

**Comment by longsleep** [comment]
I investigated and this icon is shown only when something was blocked. It usually is third party cookie or something similar. Allowing works just fine for me.
