### ISSUE TITLE
Qwant omni search should use type web

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#15]
When search from the omni box with Qwant, it currently searches in "all" sources where it should only search in the web mode. We should add &t=web parameter.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-June/000350.html

**Comment by jengelh** [comment]
What other types would it search?

**Comment by longsleep** [comment]
By default it searches in all types including videos and images. The results are quite scary and it should not search in these sources from the omni box.

**Comment by fancycode** [comment]
Fixed in 43.6-rc1
