### ISSUE TITLE
Rendering of webpage - always get Aw Snap 

### ISSUE THREAD

**Issue by theurere** [iridium-browser/iridium-browser#16]
Ubuntu 12.04
iridium-browser 43.0.2357.85-0iridium43.1+1ppa1~precise1

When I visit `http://kunden.struktur.de/iridiumbrowser/test/` I always get the Aw Snap screen. Creating a new profile doesn't help.

**Comment by fancycode** [comment]
Can you try running from the commandline (execute `iridium-browser`).

**Comment by theurere** [comment]
Doing an `apt-get upgrade` fixed the issue.
