### ISSUE TITLE
Disable voice search / hotword detection

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#21]
While Iridium does not enable Google search by default and thus also does not download or enable any hotword detection by default it still could be made to do it by changing the settings.

-  We should investigate how we can disable "Audio Capture Allowed" permission.
- We should check how we can blacklist the hotword extension and not ship with it.
- We should check that when Google Search is enabled, the Shared binary module for hotword detection is not downloaded. 
- We should remove the ability to enable hotword detection in settings when Google search is enabled.

chrome://voicesearch/

I think the voice search is something no Iridium user does want to have. Possibilities to listen in should be prevented in Iridium.

**Comment by mikegioia** [comment]
I noticed in the bug thread, they may have added a way to remove Hotword during compilation:

> A build-time flag has been added for anyone that wants to build chromium without hotwording. To disable hotwording, pass "enable_hotwording=0" in your GYP_DEFINES, or "enable_hotwording = false" in your GN config. This will prevent the shared module from being downloaded, and also prevent the option from showing up in settings.

That's from: https://code.google.com/p/chromium/issues/detail?id=491435

**Comment by longsleep** [comment]
Yes. But this is in head. We need to watch closely when we merge 45 or probably 46 or if this is backported to 44.

**Comment by fancycode** [comment]
The changes from http://crrev.com/f269d3b548203e217e8c0080c2e22e7ae3efb51e are part of Iridium 43.5 (with hotwording disabled by default):
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/hotword-disable-at-build-time-by-default.patch?h=patchview

Release builds are running and should be available shortly.
