### ISSUE TITLE
Annoying notification bars with trk 165

### ISSUE THREAD

**Issue by shvgn** [iridium-browser/iridium-browser#22]
Yesterday I installed Iridium. I receive this notifications often. The version is 43.4 on OS X. It appears on most pages I visit.

![2015-06-19 03-53-44 twitter](https://cloud.githubusercontent.com/assets/5133540/8256227/354c37dc-16ae-11e5-9f83-17e9e5f769b9.png)

I don't understand what is it, thought I tried to do the search. I saw several mentions of "trk URL"s in the release history but no description for end user, no FAQ or wiki. I guess it has something to do with tracking techniques incorporated in Chromium.

If it says that I'm tracked then I probably should expect the tracking parts to be deleted in next releases. Otherwise I don't understand why this thing shows up at least because a user is not meant to make a decision except closing the bar. Why bother than?

**Comment by fancycode** [comment]
`trk 165` is the safebrowsing database. Changing/removing this is already tracked in #10.

We assigned unique `trk` ids to each request that connects to Google to help finding the origin in the codebase, so we can remove them over the next releases.

**Comment by shvgn** [comment]
I see. Thanks for the clarification.

**Comment by longsleep** [comment]
Duplicate with #10
