### ISSUE TITLE
Delete the "Sign in to Iridium..." menu entry

### ISSUE THREAD

**Issue by shvgn** [iridium-browser/iridium-browser#23]
I thought this menu entry could be deleted since signing in is disabled. Although removing the redundant interface part is just a cosmetic change and it is a low-priority issue, on the other hand I assume it might be easy to do.

**Comment by longsleep** [comment]
We try to make the sign in work - for people who might want it but still want the other benefits from Iridium.

The reason that is not works, is the oauth scope is wrong. It is prefixed with our trk:181 identifier and thus the request fails:

POST https://accounts.google.com/o/oauth2/programmatic_auth?authuser=0

Among other data, it posts the scope.
scope=trk:181:https://www.google.com/accounts/OAuthLogin&client_id=dummytoken&device_type=chrome

The solution is to strip trk:181 before the OAUTH post and sign in should work.

**Comment by longsleep** [comment]
See #27 for sign in fix tracking.

**Comment by shvgn** [comment]
Ok. This is wontfix, i guess.

**Comment by longsleep** [comment]
As we are unable to provide Sign in with Iridium, we decided to remove the menu entry.

**Comment by longsleep** [comment]
See http://lists.inai.de/pipermail/iridium/2015-October/000508.html for patch.
