### ISSUE TITLE
Fix "Sign in to Iridium ..."

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#27]
We could easily fix Sign in to Iridium, by stipping the trk prefix before using it as OAUTH scope.

POST https://accounts.google.com/o/oauth2/programmatic_auth?authuser=0

Among other data, it posts the scope.
scope=trk:181:https://www.google.com/accounts/OAuthLogin&client_id=dummytoken&device_type=chrome

The solution is to strip trk:181 before the OAUTH post and sign in should work.

**Comment by axel668** [comment]
would be great if sign in could be supported, when using encryption with a (good) pass phrase it should be safe to use

**Comment by fancycode** [comment]
I think we can just remove the `trk:181` prefix for that URL as it seems to be only sent as `scope` and not used to perform actual requests.

**Comment by longsleep** [comment]
Might be problematic in the future though if upstream decides to use the value for something else.

**Comment by fancycode** [comment]
Removing the `trk` prefix is not sufficient. We would need a Google API key to be able to perform the OAuth requests necessary for login (login is implemented in [google_apis/gaia](https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/google_apis/gaia), API key specific data is fetched in [gaia_urls.cc](https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/google_apis/gaia/gaia_urls.cc#n89)).

I'm not sure if we want to get API keys for that or better disable the functionality for now...

**Comment by longsleep** [comment]
+1 for disable.

**Comment by eternal-sorrow** [comment]
+1 for fix and enable

**Comment by fancycode** [comment]
Enabling sign-in would require us to get Google API keys which then will be used by various other services that talk to Google - which is something we actually are working to remove with Iridium. Therefore the immediate solution is to disable the (currently not working) sign-in feature.

Patches that solve the problem otherwise are of course always welcome ;-)

**Comment by eternal-sorrow** [comment]
Browser without a sync feature is unusable. I don't want to manually import bookmarks and install all extensions every time I install browser. If you disable google sync, add some another way to sync user data.

**Comment by longsleep** [comment]
There should be other ways using an extension. @fancycode what Gogole API key is required? Can you please provide a link with details.

**Comment by fancycode** [comment]
This should be the API keys described here: https://www.chromium.org/developers/how-tos/api-keys

From this page:

"Getting Keys for Your Chromium Derivative
Many of the Google APIs used by Chromium code are specific to Google Chrome and not intended for use in derived products.  In the API Console (http://developers.google.com/console) you may be able to purchase additional quota for some of the APIs listed above. **For APIs that do not have a "Pricing" link, additional quota is not available for purchase.**"

I will get a key for myself and try this locally.

**Comment by fancycode** [comment]
Quota for the Chrome Sync API is 100 requests/day and there doesn't seem to be a way to increase it.

A PM for Chrome Sync wrote in 2013 "We don't support the sync API for use outside of Google Chrome, so we can't provide increased quota and I don't recommend relying it on it for non-personal use." (Thread at https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/kCBAIqM60ks). I couldn't find more recent information yet.

**Comment by eternal-sorrow** [comment]
could you provide a possibility for user to get google api keys by himself to make sync feature work?

**Comment by longsleep** [comment]
It is out of our current scope to fix Google sign in for syncing. We decided to remove the menu entry with one of the next Iridium releases.

**Comment by eternal-sorrow** [comment]
If this feature will not be implemented, then Iridium is unusable as a default browser.
