### ISSUE TITLE
Always run iridium with --show-component-extension-options option

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#28]
`--show-component-extension-options` command line parameter should be on by default so people actually can see the component extensions (and disable them).

Component extensions in Iridium as of now are: 
- Bookmark Manager
- Chromium PDF Viewer
- CryptoTokenExtension

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-June/000427.html

**Comment by fancycode** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/extensions-always-show-component-extensions-in-the-e.patch?h=patchview
