### ISSUE TITLE
How to install flash player on Mac?

### ISSUE THREAD

**Issue by wpoosanguansit** [iridium-browser/iridium-browser#3]
I tried to install flash player but I am still not able to so far.  Is there a special version of flash player or special instruction needed to install the player?  Thanks for your help.

**Comment by BatemanPatrick** [comment]
I had some troubles in the Windows version, too. I "solved" the problem by downloading and extracting Google Chrome and copying the "pepflashplayer.dll" (".so" on Mac?) to the Iridium folder. After that i created an Iridium-Link with the Parameters `--ppapi-flash-path=<path to>\pepflashplayer.dll`

**Comment by longsleep** [comment]
Can you guys give some example why you need Flash? If it is a common desire to have Flash in Iridium we might want to consider to add some instructions. Right now we consider Flash as insecure and for this reason cannot recomment do add it into Iridium.

**Comment by BatemanPatrick** [comment]
I know. Flash is bad, and i should feel bad ;) But there are plenty of corners in the web that still use some weird Flash based Video/Audio-Players or other stuff that depends on it. So as long i'll encouter sites that didn't hear about HTML5/ECMAScript5/6 i still need Flash or some alternative (Shumway for Iridium?).

P.S.:
The same applies to java.

**Comment by longsleep** [comment]
@Ivansss can you please check and provide instructions how one can do it.

**Comment by jeifour** [comment]
This works on OS X:
* Go to https://get.adobe.com/flashplayer/otherversions/
* Choose OS X and then FP for Opera/Chromium (PPAPI)
* Download and install
* Start Iridium by opening Terminal and writing
```
open /Applications/Iridium.app/ --args --ppapi-flash-path=/Library/Internet\ Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin/
```
Maybe you have to change paths accordingly. Iridium will warn you that the Flash Player version is outdated and urge you to update, however you can easily verify that it is indeed up to date by viewing the Info.plist file somewhere inside the PepperFlashPlayer.plugin folder in a text editor, it includes a version string. You can compare it to https://www.adobe.com/software/flash/about/

**Comment by longsleep** [comment]
Thanks for the details. It is intersting that Iridium thinks that the plugin is outdated though - i guess that is something we need to check.
