### ISSUE TITLE
Autofill triggers trk:158

### ISSUE THREAD

**Issue by eternal-sorrow** [iridium-browser/iridium-browser#30]
Is there the way to disable these annoying popups (yellow line under the address panel) with something like "Loading traced URL: trk:XXX:https:clients1.google.com/tpbproxy/af/query?client=Chromium"?
XXX is some number, for example 158. Popups appear very often (almost on every page I visit) and do not close automatically.

**Comment by longsleep** [comment]
These notifications are required so we get reports if something goes on what should be prevented. So whenever you see them it let us know. Please provide us with the exact trk:XXX number which you are seeing with any more detail you have. See #18, #19 and #10 for tracking of individual requests which are pending to be removed / cached.

**Comment by eternal-sorrow** [comment]
At least trk:158 I see at this moment.

**Comment by eternal-sorrow** [comment]
So? Is this going to be fixed? It's impossible to use iridium at this moment with all these annoyances. Maybe you should output this information using any other way? Service page on chrome:// URL or just simple console output?

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-July/000441.html

**Comment by fancycode** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/autofill-disable-autofill-entry-and-autofill-downloa.patch?h=patchview

**Comment by eternal-sorrow** [comment]
Thanks! When this change will be in binary windows build? Is there any release schedule?

**Comment by fancycode** [comment]
We don't have a fixed release schedule, but the next version should hopefully be released sometime next week or the week after that.

**Comment by eternal-sorrow** [comment]
Maybe rain maybe snow maybe yes maybe no...

**Comment by fancycode** [comment]
Yep :smiley:

Sorry for not being clearer on the timeframe...
