### ISSUE TITLE
Prefetch resource and Google Cloud Print should be off but are enabled by default

### ISSUE THREAD

**Issue by theurere** [iridium-browser/iridium-browser#31]
The iridium-browser has the following settings enabled:
  * Privacy
    - Prefetch resources to load pages more quickly
    - Enable phishing and malware protection.
  * Google Cloud Print
    - Show notifications when new printers are detected on the network System

Ubuntu 14.04
iridium-browser 43.0.2357.125-0iridium43.5+1ppa1~trusty1

**Comment by longsleep** [comment]
Should be turned off:
- Prefetch resources to load pages more quickly 
- Show notifications when new printers are detected on the network System

Should be turned on by default:
- Prefetch resources to load pages more quickly

**Comment by fancycode** [comment]
We can't turn prefetching both off and on by default :smile: I think it should be turned off by default. What do you meant should be turned on?

**Comment by longsleep** [comment]
Err - meant "Enable phishing and malware protection". Updated.

**Comment by fancycode** [comment]
"Prefetching" and "Phishing and malware protection" settings are already correct with 43.6-rc1.

Notifications for printers need to be changed.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-June/000429.html

**Comment by fancycode** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/cloud-print-disable-in-prefs-and-component-loader.patch?h=patchview
