### ISSUE TITLE
New tab opens "New tab page" for less than a second and then shows qwant

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#32]
In 43.6rc1 qwant home page is loaded on new tab. New tab page should be shown and stay - Qwant should not open when a new tab / window is created.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-July/000439.html

**Comment by fancycode** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/search-show-blank-tab-for-new-tab-page.patch?h=patchview
