### ISSUE TITLE
Do not track about:blank

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#33]
What sense does it make to track about:black usage? trk:122:about:blank should be just about:blank as nothing is transmitted.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-July/000439.html

**Comment by fancycode** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/promo-disable-Google-promotion-fetching.patch?h=patchview
