### ISSUE TITLE
how to install extensions

### ISSUE THREAD

**Issue by tristan-k** [iridium-browser/iridium-browser#35]
I tried installing the ublock extension by making a folder inside the iridium config directory with `mkdir -p ~/.config/iridium/Default/Extensions` and unzipped the archive. Then I dragged and dropped the folder into `chrome://extensions/` but shortly after some browsing the extension was deleted from the directory.

**Comment by longsleep** [comment]
Iridium should install Extensions from Chrome Web Store just fine. Why did you create the folder manually? Please also provide your platform so we can try to reproduce.

**Comment by longsleep** [comment]
Extensions from Chrome Web Store work just fine with Iridium. Please reopen when still an issue.
