### ISSUE TITLE
Get rid of cookies set by background requests

### ISSUE THREAD

**Issue by longsleep** [iridium-browser/iridium-browser#37]
Some background requests could set cookies and send cookies with them. Receiving and sending cookies from any background requests should be impossible with Iridium.

**Comment by fancycode** [comment]
This can be done by calling `SetLoadFlags` on the `net::URLFetcher` instance where you want to have this behaviour and include the flags `net::LOAD_DO_NOT_SAVE_COOKIES` and `net::LOAD_DO_NOT_SEND_COOKIES`.

I'll prepare a patch to change this for the safebrowsing requests shortly.

**Comment by fancycode** [comment]
Safebrowsing changes:
http://lists.inai.de/pipermail/iridium/2015-July/000472.html

**Comment by fancycode** [comment]
Disabled for safebrowsing in 44.0.

@longsleep: which other background requests did you see that send cookies?

**Comment by longsleep** [comment]
I guess I am good for now.
