### ISSUE TITLE
New tab page defaults to website and cannot be changed

### ISSUE THREAD

**Issue by gandaro** [iridium-browser/iridium-browser#4]
The “New tab” page is set to DuckDuckGo, and there is no option in the Settings to change it! 

As this is supposed to be a privacy-oriented browser,  why do you want DuckDuckGo to know every time I open a new tab?

What is wrong with the default New Tab page in Chromium?  I find it very useful, and I don’t see how it impacts privacy in a bad way.

If I want to use a search engine, I can type into the “omnibox”, I don’t have to be on the website, which also takes time to load.

**Comment by longsleep** [comment]
Thanks for your feedback. I agree that it is a bad thing to load DuckDuckGo in new tab. We will change this asap.

**Comment by fancycode** [comment]
For 43.1 this has switched to Quant, so I'm assuming it is opening the default search engine on new tabs. Agreed that this needs to be changed.

**Comment by jengelh** [comment]
This change can be blamed on Google - they removed setting arbitrary pages for new tabs I hear.
http://www.computerworld.com/article/2475945/internet/a-new-way-to-avoid-chrome-s-new-new-tab-page.html
Must. Eradicate. New Tab Page default. :)

**Comment by longsleep** [comment]
I think we should change it to the default behavior. There is no need to change it by the user. If a user really wants to change it, it can be done by an extension. I am using https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij?utm_source=chrome-app-launcher-info-dialog since ages.

**Comment by jengelh** [comment]
The default (Chromium) behavior is to show google.com in a new tab. That cannot possibly be what you intended to say.

I found we have two options now: show a custom URL (like about:blank), or show a row of thumbnails of most visited pages.
And I am in favor of about:blank :-)

**Comment by longsleep** [comment]
I was under the impression that chromium shows the about:apps page in new tabs. About:blank is fine with me as well.

**Comment by longsleep** [comment]
Default Chromium behavior has been restored in Iridium 43.2 and later.
