### ISSUE TITLE
Difference between 2 versions

### ISSUE THREAD

**Issue by kalvinator** [iridium-browser/iridium-browser#43]
Hi,

What is the difference between the "iridiumbrowser-44.0.0-extra-x64.msi" and the " iridiumbrowser-44.0.0-x64.msi" ?

Also, is it possible to change the default folder installation? When I try to change it in to "the program files", it ask me to get administrator rights but if I right-click on the msi installer, there is no option to run it with administrator privileges.

thx.

**Comment by longsleep** [comment]
Hi,

the difference is that -extra contains additional media codecs. 

These are the currently available windows variants:

- Iridium without non-free media codecs (like before).
- Iridium-extra includes non-free media codecs.
- Iridium is now also released as as zip archive, which
  does not require installation (portable edition).

I guess we need a wiki page for this.

**Comment by tgaff** [comment]
Please consider adding this information to the product website.  Users should know which one they should download (without having to search github).

**Comment by corysimmons** [comment]
Is the site open source? Someone could contribute little tidbits like this.

**Comment by sergeevabc** [comment]
@longsleep, it is doubtful to call Iridium portable since it creates profile folder within C:\Users\...
True portable modification like [SrWare Iron](http://www.srware.net/downloads/IronPortable.zip) keeps profile near, i.e. in the same folder where the whole package was extracted to. Could you comment it?
