### ISSUE TITLE
Installation on Windows 10

### ISSUE THREAD

**Issue by souldanger** [iridium-browser/iridium-browser#44]
when installing with Win10, you get asked to install on a local drive.
But even when I use a local drive, it would not let me install it...

**Comment by longsleep** [comment]
Hi,

what does happen - please give us more details?

In the meantime, you can use a portable edition (shipped as a .ZIP file which does not require installation). https://downloads.iridiumbrowser.de/windows/44.0.0/

**Comment by longsleep** [comment]
iridium on Windows does install into C:\Users\${USER}\AppData\Local\Program\Iridium\ by default. I was not able to reproduce any issue with that. Please reopen the issue when you have more details.

**Comment by longsleep** [comment]
If somone encounters an installation issue please try to create a log

```
msiexec /i "C:\MyPackage\Example.msi" /L*V "C:\log\example.log"
```
