### ISSUE TITLE
FreeBSD / OpenBSD support?

### ISSUE THREAD

**Issue by rene0** [iridium-browser/iridium-browser#47]
The Chromium browser is unofficially ported to both FreeBSD and OpenBSD, but the Google Chrome team does not consider *BSD an official platform, see e.g.
https://code.google.com/p/chromium/issues/detail?id=352587

From this ticket it can be seen that whether or not *BSD should be supported in the first place differs from one developer to the next. Is there any standpoint from you on this?

**Comment by longsleep** [comment]
OpenBSD community seems to have ported Iridium - See http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/www/iridium/ or http://ports.su/www/iridium - so you should be able to just install it on OpenBSD. We currently have nobody to provide official iridium builds for *BSD.

**Comment by longsleep** [comment]
No further feedback, assuming it just works.
