### ISSUE TITLE
Slight bug in El Capitan

### ISSUE THREAD

**Issue by 314parley** [iridium-browser/iridium-browser#48]
There appears to be an issue in the address bar, where everything is bold. (see below)
![screen shot 2015-10-05 at 10 43 16 am](https://cloud.githubusercontent.com/assets/1246441/10288504/225ef6c4-6b4e-11e5-8b33-764b3c453d7e.png)

Strangely, Google appears to have fixed it in Chrome.
![screen shot 2015-10-05 at 10 50 00 am](https://cloud.githubusercontent.com/assets/1246441/10288631/ebbd2ff4-6b4e-11e5-9fd4-c4d9a7c048dd.png)

it's a minor bug, but I would like Iridium to be perfect. I'm recommending it as much as I can in my imageboard community (314chan) and I appreciate all of what you do.

**Comment by longsleep** [comment]
Thanks for the report. Iridium should automatically get the fix from Chromium upstream with the next release.

**Comment by fancycode** [comment]
@ivansss: could you please verify this is working after compiling 46.0rc1?

**Comment by Ivansss** [comment]
This issue is fixed in Iridium 46.0 for Mac OS X.

**Comment by 314parley** [comment]
Forgot to close this when they fixed it. Thanks Again!
