### ISSUE TITLE
Mouse events not triggered

### ISSUE THREAD

**Issue by theurere** [iridium-browser/iridium-browser#5]
Tested on Fedora 21 with iridium-browser 41.2.

When hovering over a link or button the default cursor does not change to a pointer and no hover state on the element is triggered.

I installed google-chrome-stable Version 42.0.2311.135 (64-bit) and the issue is the same. 
google-chrome-unstable Version 44.0.2391.0 dev (64-bit) fixed the issue.

**Comment by longsleep** [comment]
Can you identify the commit which fixed the issue in the Chromium repository?

**Comment by theurere** [comment]
Seems to be Virtualbox specific:
`https://chromium.googlesource.com/chromium/src.git/+/ad780aadaade136c6ac1711d9d0a8ebccde3d8a1`

**Comment by longsleep** [comment]
So this is not fixed in 43?

**Comment by fancycode** [comment]
That commit is included in 43.1
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/commit/ui/events/devices/x11/touch_factory_x11.cc?id=ad780aadaade136c6ac1711d9d0a8ebccde3d8a1
