### ISSUE TITLE
1password can not fill the forms

### ISSUE THREAD

**Issue by am0oma** [iridium-browser/iridium-browser#50]
when I click to fill the password using 1password extenstion ... 1password said code signature could not be verified ... 

![issue 1password](https://cloud.githubusercontent.com/assets/2161879/10461349/3815f31e-71d9-11e5-8bf1-c3c7a36db72b.jpg)

**Comment by longsleep** [comment]
Not sure if we can change this. Iridium for mac is currently not code signed and thus the default configuration of 1password will not use it.

See the guide at https://guides.agilebits.com/1password-mac-kb/5/en/topic/code-signature-could-not-be-verified for explanation and how to turn this validation of in 1password.

We might investigate how and if it is possible to provide code signed releases for Mac without App store.
