### ISSUE TITLE
Audio/playback issues (on mac)

### ISSUE THREAD

**Issue by JustTor** [iridium-browser/iridium-browser#51]
Audio won't play on some websites (soundcloud and volafile) with Iridium. They work fine in Chrome. My friend told me that both those sites use SoundManager2, which uses HTML5 audio. I am using OSX 10.10 and have tested with the latest version of Iridium

**Comment by longsleep** [comment]
Hi, thanks for the report - we will investigate.

**Comment by theurere** [comment]
It seems to be related to not using the `-extra` version of iridium-browser. Ubuntu includes the `iridium-codecs-ffmpeg-extra` package by default. The following error was written to the console when trying to play demo files from [jplayer.org](http://jplayer.org/HTML5.Audio.Support/) under 'Tests Available':
```
[Error:render_media_log.cc(18)] MedaiEvent: PIPELINE_ERROR demuxer: could not open
```

**Comment by longsleep** [comment]
@JustTor : Iridium does only ship free and open codecs by default. If you wish to use proprietary or patented codecs install the -extra variant of Iridium. You find the download for the -extra version in the version subfolder of Iridium (for example: https://downloads.iridiumbrowser.de/macosx/44.1.0/ for Mac OS Iridium 44.1.0).

**Comment by JustTor** [comment]
Thanks, that seems to have fixed my issue. I've noticed you don't have any description on any files or folders, but I would like to at least suggest that you may add a short description that explains the difference between each version (for the convenience of other users new to your browser).
