### ISSUE TITLE
Problem with windows 10 latest release

### ISSUE THREAD

**Issue by kalvinator** [iridium-browser/iridium-browser#54]
Hi,

I have just encountered a major issue with the browser with the windows 10 latest update (build 10586). I just cannot start the browser... 

I try to reinstall it, but I cannot able to load it and start it.

**Comment by souldanger** [comment]
Please try again with latest release: [https://downloads.iridiumbrowser.de/windows/](https://downloads.iridiumbrowser.de/windows/)
