### ISSUE TITLE
Iridium phones home to iridiumbrowser.de

### ISSUE THREAD

**Issue by teresaejunior** [iridium-browser/iridium-browser#55]
I have requested Iridium to be included in the "Best Browser of the Year" contest at LinuxQuestions.org https://www.linuxquestions.org/questions/showthread.php?p=5474207 and it was somewhat a bit embarrassing a comment that one user made: "It may not call google, but it does "call home" to Iridium and if you "deny" it, the browser refuses to work."

I had read about this on Hacker News a few months ago, and thought this was left only for debugging for that time and was later fixed, but it seems to have been left permanently! Couldn't the Google Server requests be just redirected to 127.0.0.1?

And just like someone said on Hacker News: "Have you ever seen the underhanded C contests? There are far too many ways for something like this to turn nasty.", even if the Iridium team has not any bad intentions!

Thank you for Iridium, it has been working very well in my Debian Wheezy system!

**Comment by jengelh** [comment]
iridiumbrowser.de is contacted for the Safe Browsing/Antiphishing/Bad Plugin lists, a feature which we have deemed important enough to keep enabled by default. You can turn that off in the Settings.

If there is anything else, do elaborate. "refuses to work" is not a sufficient description of the error - how do you "deny" it, what is "it", and how does that refusal manifest?

**Comment by teresaejunior** [comment]
Hello, thanks for your answer!

I have never tried blocking the Iridium servers, that was reported by another user in that link.

Regarding Iridium contacting iridium.de for the Safe Browsing/Antiphishing/Bad Plugin lists, I honestly have not found anything about it in the description or the Wiki. When users do a Google Search of Iridium though, the only information they can find about this is that conversation on Hacker News, where the Iridium developers answer saying that this was left only for debugging.

**Comment by jengelh** [comment]
The hackernews thread is ancient by now. The debugging thing mentioned there has been replaced in iridium-43 with an improved solution that does not involve iridiumbrowser.de anymore.

**Comment by teresaejunior** [comment]
OK, may I suggest to update the page https://github.com/iridium-browser/iridium-browser/wiki/Differences-between-Iridium-and-Chromium with this information? 

It still says the following: "Iridium has Google Safe Browsing enabled by default. This means within 5 minutes after start and then every 30 minutes a request to Google is made to update the local safe browsing data base.".

**Comment by ohnonot** [comment]
> The debugging thing mentioned there has been replaced in iridium-43 with an improved solution that does not involve iridiumbrowser.de anymore.
the expression "an improved solution" is not really satisfying (me).
what has it been replaced with?
i think it is possible to explain that in just a few more words?
thanks.

**Comment by h-2** [comment]
> i think it is possible to explain that in just a few more words?

yes, please!

**Comment by h-2** [comment]
I would also propose that by default **no homecalling* is active of any sort. You can ask on first start if users wish to activate it, but it shouldn't be on by default IMHO.
After all privacy is the "selling point" of Iridium :)

**Comment by jengelh** [comment]
URLs like clients1.google.com/blahblah were replaced by http://trk-123.iridiumbrowser.de/clients1.google.com/blah , so there we would be able to observe, by looking at Apache's access.log, if and when the browser tries a suspicious URL.
This suffers from problems: not all developers, let alone users, have a way to access that logfile.
So it was replaced in v43 by a client-side-only notification mechanism. URIs now look like "trk:123:http://clients1.google.com/blah" and if the browser tries to load anything from the trk: scheme space, it will show a yellow bar (and continue loading the real URL behind it).

h-2: Turning off safebrowsing would actually make the project _less secure_ in our opinion.

**Comment by ohnonot** [comment]
thanks for the explanation.
there's no judgement either way from my side, i just found the wording a little shady... :-)

**Comment by h-2** [comment]
> h-2: Turning off safebrowsing would actually make the project less secure in our opinion.

Thanks for making this clear. Can you clarify which of the problems raised here apply:
https://en.wikipedia.org/wiki/Google_Safe_Browsing#Privacy

I.e: does Iridium transmit url-hashes by default, or full URLs? 
Does it create this "preferences cookie"?
What about the "client-side checks"?

**Comment by jengelh** [comment]
Reporting code was disabled by these commits:

safe_browsing: disable cookie transmission
safe_browsing: disable reporting of safebrowsing override
safe_browsing: disable incident reporting

Barring oversights, the browser is supposed to only use the static SB lists, regularly downloaded from cache.iridiumbrowser.de.

**Comment by h-2** [comment]
@jengelh  Ah, ok, that sounds good, thanks! Out of curiosity: The static SB lists are checked locally against the URLs I go to, or are they checked by your servers?
