### ISSUE TITLE
Can't play videos in Facebook

### ISSUE THREAD

**Issue by drsnugglesx** [iridium-browser/iridium-browser#64]
Iridium seems unable to play videos in Facebook, I also have problems playing videos on other websites. Using Iridium 48.2.

**Comment by crni536** [comment]
Can confirm this, but seems to be related to Flash for whatever reason. 
Running 48.2 x64 which was installed with the .msi file.
Checked on Facebook, Twitter and some older Youtube videos, here are the screenshots:
![iridium_2016-03-12_13-21-46](https://cloud.githubusercontent.com/assets/8262850/13722943/21e34b52-e856-11e5-9510-179bdea784d5.jpg)
![iridium_2016-03-12_13-20-07](https://cloud.githubusercontent.com/assets/8262850/13722944/21e8c2ee-e856-11e5-8831-b12fa93823d5.jpg)
![iridium_2016-03-12_13-20-49](https://cloud.githubusercontent.com/assets/8262850/13722945/21eb4302-e856-11e5-9f65-8f85d150ff02.jpg)

**Comment by hockeymikey** [comment]
I can not produce.  I am running 48.2 x64 and video is working fine for me.  Facebook, Twitch and Youtube all work fine.  Try reinstalling and see if that fixes anything.  I used to have video issues in 47.x but was fixed after I upgraded to 48.2.

**Comment by souldanger** [comment]
Hi guys
please install latest version from [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)  and most audio/video will work.
However some sites require other extensions or codecs, some proprietary, that Iridium does not use for many reasons. But feel free to add any extension or codec from chrome://extensions/ or other.
Thanks!
