### ISSUE TITLE
[48.2 x64] 'Class not registered'

### ISSUE THREAD

**Issue by Tharn** [iridium-browser/iridium-browser#65]
Hi,

After installing Iridium, it becomes impossible to put an icon on the Taskbar. Either:

- You launch the Iridium.exe and right-click the taskbar icon to 'pin to taskbar', in which case every time you click on it, it will spawn a second process and ignore the icon you placed. or,
- You directly select the Iridium.exe and 'pin to taskbar', in which case you get an error saying 'Class not registered'.

This appears to have been a very old Chrome/Chromium bug that somehow made it into a recent Iridium build, but I couldn't fix it by going into the registry as advised. It seems to be related to system-wide installs vs. traditional Chromium in \Appdata\Local.(http://superuser.com/questions/503489/chrome-doesnt-start-in-windows-8-gives-an-error-message-class-not-registered)

**Comment by nconder** [comment]
I have this problem when trying to open links with other programs like Outlook for example. 

`"Something unexpected went wrong with thus URL:
"---- some url here----" Class not registered.`

I have triple checked that iridium is set as the default browser system wide.

**Comment by fariparedes** [comment]
Can confirm this is still an issue as of 51.1. You cannot open Iridium from the taskbar and you cannot open links when Iridium is your default browser.

**Comment by souldanger** [comment]
Please use the latest release from [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)  
Thanks!

**Comment by nconder** [comment]
@souldanger working great now thank you!
