### ISSUE TITLE
[48.2 x64] Installer folder permissions

### ISSUE THREAD

**Issue by Tharn** [iridium-browser/iridium-browser#66]
When running the .msi installer, we are given a choice where to install the browser. Trying to use C:\Program Files\Iridium gives me a permission error that I can only circumvent by running a command prompt as administrator and manually starting the .msi through that, or previously creating the Iridium folder by hand. The installer should have the privileges to do this itself.

**Comment by souldanger** [comment]
Hi Tharn,
please install latest  version from [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)
Thanks
