### ISSUE TITLE
The first thing this browser does is connect to Google...

### ISSUE THREAD

**Issue by rugk** [iridium-browser/iridium-browser#68]
I just installed this browser and the first thing it did was connecting to `tools.google.com`over port 80, so it does not even use HTTPS. 
The reason seems to be that it wants to show me a "welcome page" on http://tools.google.com/chrome/intl/de/welcome.html.

What a wonderful start for a browser which promises privacy and it is said it would not call home to Google.

**Comment by EnMod** [comment]
It doesn't seem like a "call home" so much as a default http request that occurs on launch.  All Chromium projects seem to start that way.  The "calling home" parts I thought were supposed to be all the tracking/data collection happening under the hood?

**Comment by medozas** [comment]
@rugk : Well, that is something different indeed as @EnMod points out. We have made some improvements though, and we are continueing to do so. Basically our intention is to make a special master_preferences file (which is normally altered by distros) to show some non-google page in the future. This indeed is not a "connect to google"-page in the terms that the browser really is compromised permanently. Next to that this is "just" the welcome page. Already with second start this does not happen. I'm therefore closing this issue ... Stay tuned for a different welcome page in the future.
