### ISSUE TITLE
[OS X] "extra" variant differences?

### ISSUE THREAD

**Issue by brevilo** [iridium-browser/iridium-browser#69]
How does the ["extra" variant](https://downloads.iridiumbrowser.de/macosx/48.2.0/) differ from the regular OS X release?

Thanks

**Comment by brevilo** [comment]
Ah, according to https://github.com/iridium-browser/iridium-browser/issues/43 it contains non-free media codecs. Is that statement about the windows variants applicable to OS X as well? What exactly gets added to "extra"?

Yes, a wiki page would help :+1:

**Comment by tgaff** [comment]
echoing from #43 : Please consider adding this information to the product website. Users should know which one they should download (without having to search github).

**Comment by souldanger** [comment]
Thanks - we have finally added this to the Download page of our website!
