### ISSUE TITLE
Iridium default application for windows internet bookmarks

### ISSUE THREAD

**Issue by MichaelWeh** [iridium-browser/iridium-browser#7]
After installing Iridium all internet-desktop-links are connected to Iridium.

But there is no klass installed to open such links.

**Comment by longsleep** [comment]
This is probably platform specific? Please add your platform and version.

**Comment by MichaelWeh** [comment]
Windows 8.1
The screen shows the affected links/icons.
![screenshot 1](https://cloud.githubusercontent.com/assets/12396216/7581224/a31ba258-f880-11e4-904c-47909a4f6840.png)

**Comment by longsleep** [comment]
Now tracked at https://github.com/iridium-browser/iridium-browser-windows/issues/6
