### ISSUE TITLE
Update ubuntu binaries

### ISSUE THREAD

**Issue by triceratops1** [iridium-browser/iridium-browser#72]
please, can you give binaries for ubuntu wily and xenial?
https://downloads.iridiumbrowser.de/ubuntu/

**Comment by peyloride** [comment]
+1 I have same problem. I cant install because of this.

**Comment by rafaelrpinto** [comment]
See #88

**Comment by alindt** [comment]
+1 Please add Xenial builds to Ubuntu repo

**Comment by souldanger** [comment]
Hi All
we are happy and even a bit proud to announce that finally v54.0 for Ubuntu and OpenSUSE is available in the download section [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)
