### ISSUE TITLE
Several Audio / Video players that work on Chromium don't work on Iridium

### ISSUE THREAD

**Issue by cesarbrie** [iridium-browser/iridium-browser#77]
I've been using Chromium (on Arch Linux 64 and without a Flash Player plug-in) to listen to podcasts on SoundCloud without a problem for months. Now I switched to Iridium and they don't work anymore. It's as if the HTML media in general was failing somehow. Although not in all cases.

- Test for SoundCloud: https://soundcloud.com/lifeofdesiigner/desiigner-panda
- Vines don't seem to be working either: https://vine.co/v/hbUevjMq5L9
- Same with Tumblr videos: http://fydokyungsoo.tumblr.com/post/145748510654/fancam-160611-do-music-core-monster (See issue #71)
- Same with Twitter: https://twitter.com/codorniou/status/742314227172540416
- Or at least some because this one does work for me: - https://twitter.com/ABCmediawatch/status/742288784503406592
- Some users also reported having problems with Facebook, Twitch, and YouTube on Issue #64: https://github.com/iridium-browser/iridium-browser/issues/64

I created a new issue because it seemed to me that none of the existing ones were broad enough in their description of this issue.

Please, fix this. Although I can wait a few days for this. It's an absolute deal breaker for me. I do NOT want to install Flash Player and considering your approach towards Security, preventing your users from having to install Flash Player, should be a top priority issue.

Thanks a lot.

**Comment by cesarbrie** [comment]
This issues' page seems quite dead. Can somebody confirm it's not?

**Comment by HiPhish** [comment]
I have the same issue, here is a YouTube video that does not work:
https://www.youtube.com/watch?v=3N__tvmZrzc
It's individual videos, I can for example view the second lecture without issues.

**Comment by sahilamin** [comment]
This issue still exists for me, I'm running version 51.1 (Developer Build) (32-bit)

**Comment by cesarbrie** [comment]
The entire project seems to be quite dead, doesn't it? I guess I'm switching to something else soon. It's a pity. It was exactly what I was looking for.

**Comment by sirhughmunguswatt** [comment]
Also having this problem.

**Comment by souldanger** [comment]
hi guys,
this problem is down to extensions/codecs - iridium does not use all the same extensions/codecs as Chromium. 
Please understand that we cannot test any and all use cases. 
If something is not working, please try to find out what extension or codec is required and add it at your own risk.
I.e. Amazon Video requires the widevine cdm - now widevine is owned by Google, which explains why Iridium doesn't use it.
Thank you for your understanding!

**Comment by HiPhish** [comment]
@souldanger Maybe you should put that up on a FAQ or something, otherwise it looks like Iridium is broken.

**Comment by sirhughmunguswatt** [comment]
Hi, reinstalling it with the 'extra' version of Iridium that includes non-free codecs seems to have fixed it for me. Iridium keeps your bookmarks/history after uninstalling like Chrome does if you're wondering.

**Comment by souldanger** [comment]
@sirhughmunguswatt yes, we are working on becoming more transparent and have something like a FAQ on the website. This should happen with the next release at some point later this month.

**Comment by souldanger** [comment]
@sirhughmunguswatt good to hear it worked for you!
