### ISSUE TITLE
Can't install Iridium on Ubuntu 16.04

### ISSUE THREAD

**Issue by Joewind** [iridium-browser/iridium-browser#78]
I can't install Iridium on Ubuntu 16.04 using the commands on the download page: 
https://iridiumbrowser.de/download.html

The final command produces the following error:

root@j-VPCEH2H1E:~# sudo apt-get install iridium-browser
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package iridium-browser
root@j-VPCEH2H1E:~#

**Comment by philipptrenz** [comment]
At the moment Iridium is just available for precise (12.04), trusty (14.04), utopic (14.10) and vivid (15.04). I'm also very excited, if and when Iridium will reach current Ubuntu versions.

**Comment by alindt** [comment]
+1 Please add Xenial builds to Ubuntu repo (see also #72 )

**Comment by souldanger** [comment]
hi guys
the development team is working on a new release that addresses these issues.
thanks!

**Comment by fugo** [comment]
Sad that you first work on the windows version :disappointed:

**Comment by souldanger** [comment]
Hi fugo
we will have a new build for Ubuntu shortly.
thank you for your patience!

**Comment by brentadamson** [comment]
Any idea on how much longer? Thanks!

**Comment by souldanger** [comment]
Hi Brent
we are testing at present and will release once all bugs have been fixed...
However, some of our dev team are still on holidays, therefore it might take another week at least.
Thanks a bunch!

**Comment by souldanger** [comment]
Hi All
we are happy and even a bit proud to announce that finally v54.0 for Ubuntu and OpenSUSE is available in the download section [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)

**Comment by fugo** [comment]
Hi  @souldanger
I tried this
```
wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -
sudo apt-add-repository 'https://downloads.iridiumbrowser.de/ubuntu main'
sudo apt-get update
sudo apt-get install iridium-browser
```
and get `E: Paket iridium-browser kann nicht gefunden werden.`
I went to `https://downloads.iridiumbrowser.de/ubuntu/` and downloaded the file `iridium-browser_current_amd64.deb` Now I got it. :+1:

**Comment by souldanger** [comment]
thanks!
we've updated the website see [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)

**Comment by lozog** [comment]
These steps currently on the download page:
`wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/iridium-browser.list
deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
#deb-src https://downloads.iridiumbrowser.de/deb/ stable main
EOF
sudo apt-get update
sudo apt-get install iridium-browser`
didn't work for me. After the second line, it would just keep prompting for more input.

I tried the steps in fugo's post and those worked for me.

**Comment by longsleep** [comment]
> After the second line, it would just keep prompting for more input.
Prompting stops after the second EOF. 

Output It looks like this when you copy/paste it into a terminal:
```bash
~$ cat <<EOF | sudo tee /etc/apt/sources.list.d/iridium-browser.list
> deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
> #deb-src https://downloads.iridiumbrowser.de/deb/ stable main
> EOF
deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
#deb-src https://downloads.iridiumbrowser.de/deb/ stable main
~$
```

Make sure you have all the correct new lines when copy/paste (4 lines for the cat command).
