### ISSUE TITLE
doesn't work with netflix

### ISSUE THREAD

**Issue by corysimmons** [iridium-browser/iridium-browser#79]
pretty sure this might be intentional but netflix throws:

```
We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button.
```

WidevineCdm isn't in chrome://components so i'm assuming it was intentionally removed?

seems like chromium started supporting it http://alien.slackbook.org/blog/new-chromium-now-supports-netflix-natively-without-wine-plugins/

doesn't need fixed if it's intentional. just pointing out netflix is broken as the first hiccup i've ran into since migrating from chrome to iridium.

**Comment by souldanger** [comment]
Hi guys,
Widevine is a proprietary extension owned by Google, this is why Chromium uses it, but Iridium doesn't. However you can add widevine cdm by going to chrome://extensions/ - search and add it at your own risk.
So yes, Cory's guess is 100% correct - it is intentional!
Thanks!

**Comment by lebarondemerde** [comment]
Is there a way to enable Widevine/Extension per domain? I mean, have it enabled just for Netflix for instance?

Thanks!

**Comment by souldanger** [comment]
Please check with Widevine.
We don't build or use Widevine, so how could we know?
Thanks for your understanding!

**Comment by hhiru** [comment]
> However you can add widevine cdm by going to chrome://extensions/ - search and add it at your own risk

I tried doing as you suggested and it imported it (with some syntax errors in the manifest) but still I can't play anything on spotify website. Am I missing some other setting disabled by default?
![image](https://user-images.githubusercontent.com/11262717/32689327-b627d424-c6e2-11e7-8ac7-0b560217e1f0.png)

**Comment by souldanger** [comment]
Widevine is a proprietary extension owned by Google, this is why Chromium uses it, but Iridium doesn't. 
Iridium is about privacy while the widevine extension or similar are not really.
It is recommended to use a secondary browser for streaming services that require widevine or similar.
