### ISSUE TITLE
Loading experimentstatus from trk:263

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser#8]
After being open for a short while (a couple of minutes), iridium tries to load the experimentstatus:
```
Attempt at loading traced URL: trk:263:https://clients4.google.com/chrome-sync/dev/experimentstatus
```

**Comment by jengelh** [comment]
Issue is known.
http://lists.inai.de/pipermail/iridium/2015-May/000297.html
Who will be the first to find the switch for this annoying google tracker?

**Comment by longsleep** [comment]
So this happens even if you are not logged into Google?

**Comment by fancycode** [comment]
Yes. From what I have seen in other places, they refer to "experiments" for features that are implemented but not globally enabled (but could be through some commandline flags).
Perhaps these requests enable them to remotely activate features for some/all users to test them depending on the channel they are on.

However to answer this in detail, I would have to check where the request comes from and what it actually does.

**Comment by longsleep** [comment]
@theurere can you please check and get the details of this request.

**Comment by fancycode** [comment]
I'm already working on removing this.

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-June/000347.html

**Comment by jengelh** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/diff/google-cloud-messaging-disable-experiment-status-che.patch?h=patchview&id=c7566afbe7ccd54d3bb218d23f48a172263e5cf0
