### ISSUE TITLE
Windows XP & old CPU

### ISSUE THREAD

**Issue by bl83** [iridium-browser/iridium-browser#83]
Error at launch:

"The procedure entry point GetThreadId could not be located in the dynamic link library KERNEL32.DLL"

**Please build for WinXP (and compile for old CPU with with SSE2 optimizations disabled)**

Otherwise **please disclose system requirements on download page**

http://johnhaller.com/blog/2016-03-04--google-chrome-50-drops-support-for-windows-xp-vista

**Comment by Carpetsmoker** [comment]
I also had errors running this on Windows 95. Ridiculous this isn't mentioned in the system requirements page!

**Comment by souldanger** [comment]
Hi guys,
updated system requirements will be live on our website shortly.
FYI it is rather unlikely that we built anything for WinXP/Win95 or old CPU's.
We are only a small team of developers and engineers...
