### ISSUE TITLE
Update check active

### ISSUE THREAD

**Issue by fancycode** [iridium-browser/iridium-browser#9]
After being open for a short while (a couple of minutes), iridium tries to load the update status:
```
Attempt at loading traced URL: trk:170:https://clients2.google.com/service/update2
Attempt at loading traced URL: trk:171:https://clients2.google.com/service/update2
```

**Comment by fancycode** [comment]
http://lists.inai.de/pipermail/iridium/2015-May/000342.html

**Comment by mikegioia** [comment]
Is there any reason why this message is alerting for seemingly every page?

**Comment by jengelh** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/diff/updater-disable-updater-pings.patch?h=patchview&id=9c0060697635cb66eb99e23fe896e7e8a62f25ef
