### ISSUE TITLE
Wrong 'latest' version for OS X on https://downloads.iridiumbrowser.de/macosx/

### ISSUE THREAD

**Issue by larryhynes** [iridium-browser/iridium-browser#96]
The latest version of iridium available on [https://downloads.iridiumbrowser.de/macosx/](https://downloads.iridiumbrowser.de/macosx/) for Mac OS X (as of 25 Sept. 16) is `51.1.0`. However the files `iridium_browser_osx_latest.dmg` and `iridium_browser_extra_osx_latest.dmg` appear to be linked to an older version (`48.1.0`).

**Comment by ryanzarafa** [comment]
@larryhynes Thanks for the notice. Links have been fixed.
